apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
